services:
  vllm:
    container_name: vllm
    build:
      context: .
    env_file:
      - env.local
    ports:
      - "8000:8000"
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:host-gateway"
