default_language_version:
  python: python3.13
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff
      args: [
        "--fix",
        "--line-length", "120",
        "--extend-select=PLC,PLE,Q,A",
      ]
    - id: ruff-format
      args: [
        "--line-length", "120"
      ]

