include_fragments = false
exclude_all_private = true

accept = [
    "200..=299",
    # Consider a 403 to be success. Cloudflare-protected sites, like
    # https://platform.openai.com, return a 403 to lychee.
    "403"
]

exclude = [
    # OPENAI_BASE_URL is 404
    "https://api.openai.com/v1",
    # Exclude links replaced by %PUBLIC_URL%
    ".*%25PUBLIC_URL%25.*",
    # Does not respond on CI and not in any doc
    "https://www.robotstxt.org/robotstxt.html",
]

# better to be safe and avoid failures
max_retries = 6
timeout = 20
