version: v0.3.0

listeners:
  - type: model
    name: model_listener
    address: 0.0.0.0
    port: 12000
    timeout: 30s

model_providers:
  # Use ollama directly, since we can't inherit OPENAI_BASE_URL etc and need
  # to hard-code the model anyway.
  - model: openai/qwen3:0.6b
    # In native mode, Envoy runs on the host alongside ollama.
    base_url: http://localhost:11434
    default: true

tracing:
  random_sampling: 100
  trace_arch_internal: true
