services:
  litellm:
    container_name: litellm
    build:
      context: .
    env_file:
      - env.local
    ports:
      - "4000:4000"
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:host-gateway"
