# See https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
spring:
  main:
    web-application-type: none
    banner-mode: "off"
  ai:
    model:
      # Disable all models by default and enable per example to avoid eager autoconfiguration.
      # https://github.com/spring-projects/spring-ai/blob/main/spring-ai-model/src/main/java/org/springframework/ai/model/SpringAIModelProperties.java#L37
      embedding: none
      embedding.text: none
      embedding.multimodal: none
      image: none
      audio.transcription: none
      audio.speech: none
      moderation: none
    openai:
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      api-key: ${OPENAI_API_KEY:enter-your-api-key}
      chat:
        options:
          model: ${CHAT_MODEL:gpt-4o-mini}
        # ensure /v1 isn't appended twice
        completions-path: /chat/completions
    azure.openai:
      api-key: ${AZURE_OPENAI_API_KEY:}
      endpoint: ${AZURE_OPENAI_ENDPOINT:}
      chat:
        options:
          deployment-name: ${CHAT_MODEL:}

    chat:
      observations:
        log-prompt: true
        log-completion: true
        include-error-logging: true

management.observations.annotations.enabled: true

logging:
  level:
    root: WARN

    io:
      netty:
        resolver:
          dns:
            # Hush warnings about native DNS on MacOS
            DnsServerAddressStreamProviders: OFF
    org:
      springframework:
        ai:
          chat:
            observation: DEBUG
            client:
              observation: DEBUG
          model:
            chat:
              observation:
                autoconfigure:
                  # Hush warnings about prompt and completion logging
                  ChatObservationAutoConfiguration: OFF
