# See https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
spring:
  main:
    web-application-type: none
    banner-mode: "off"
  ai:
    # Right now, we cannot select azure or openai with a single property.
    # See https://github.com/spring-projects/spring-ai/issues/2712
    model:
      embedding:  ${spring.ai.model.chat}
      audio:
        transcription:  ${spring.ai.model.chat}
      image:  ${spring.ai.model.chat}
    openai:
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      api-key: ${OPENAI_API_KEY:enter-your-api-key}
      chat:
        options:
          model: ${CHAT_MODEL:gpt-4o-mini}
        # ensure /v1 isn't appended twice
        completions-path: /chat/completions
    azure.openai:
      api-key: ${AZURE_OPENAI_API_KEY:}
      endpoint: ${AZURE_OPENAI_ENDPOINT:}
      chat:
        options:
          deployment-name: ${CHAT_MODEL:}

    chat:
      observations:
        include-prompt: true
        include-completion: true
        include-error-logging: true

management.observations.annotations.enabled: true

logging:
  level:
    root: WARN
    io:
      netty:
        resolver:
          dns:
            # Hush warnings about native DNS on MacOS
            DnsServerAddressStreamProviders: OFF
    org:
      springframework:
        ai:
          model:
            chat:
              observation:
                autoconfigure:
                  # Hush warnings about prompt and completion logging
                  ChatObservationAutoConfiguration: OFF
