name: test-genai-function-calling

on:
  pull_request:
    branches:
      - main
    paths:
      - 'genai-function-calling/openai-agents/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - .pre-commit-config.yaml
      - lychee.toml
      - Makefile

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: openai-agents
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pytest --vcr-record=none
        working-directory: genai-function-calling/openai-agents
